openbuddy-llama2-13b-v8.1:
  prompt_template: "openbuddy/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "./openbuddy-llama2-13b-v8.1-fp16" # local path
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "OpenBudddy-LLaMA2-13B-v8.1"
  link: "https://huggingface.co/OpenBuddy/openbuddy-llama2-13b-v8.1-fp16"
