ultralm-13b:
  prompt_template: "ultralm-13b/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/data/ultrallama/ultrachat_llama-13b-fulldata-8500_hf-recover" # local path
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
    early_stopping: True
  pretty_name: "ultralm-13b"
  link: "/data/ultrallama/ultrachat_llama-13b-fulldata-8500_hf-recover"